[package]
name = "covid"
version = "0.1.0"
authors = ["juanval"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
anyhow = "1.0.30"
plotters = "0.2.14"
serde = { version = "1.0.110", features = ["derive"] }

